### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by ramsestom** [vishna/as2f#4]
Hi
I tried this generator but couldn't make it work on Windows 10 with VSCode.
In the VSCode terminal when executing the `flutter packages pub run as2f:codegen` command I first had the following error message:
> Trying to download as2f-699a11e9e6.jar ...
> CreateProcessW failed 2
> Failed to download https://jitpack.io/com/github/vishna/as2f/cli/699a11e9e6/cli-699a11e9e6-all.jar
> Please download the jar manually and save it to .jarCache/as2f-699a11e9e6.jar.
> Once this is complete just rerun pub command.
> pub finished with exit code 1

So I manually downloaded the jar file and re-ran the command. I then had the following error message:
> ? as2f.yaml not found, creating one for you...

with the generator hanging on forever (killed it after 2 or 3 min with CTRL+C) and the as2f.yaml was never generated. 
So I manually created the as2f.yaml and filled it with the necessary informations and rerun the command but the generator is still hanging forever (had to manually kill it once again) with no error meassage this time. Any idea of what might be the issue? (I used the strings.xml files from the carrots example for this test so the issue is not with the content of this files)

**Comment by vishna** [comment]
hmm... sorry for late response - I was busy lately. gotta look into running Windows 10 somehow 😬

**Comment by vishna** [comment]
so I changed download script a bit and managed to regenerate carrots.dart on Windows 10 (via VirtualBox)

<img width="654" alt="Screenshot 2019-12-26 at 12 13 40" src="https://user-images.githubusercontent.com/121164/71473896-4eb39580-27d9-11ea-9a2b-4c21af20bc01.png">

I need to still figure out why `dartfmt` doesn't work but once I do that I'll push a fixed version to pub.dev

**Comment by vishna** [comment]
Hey @ramsestom, thanks again for your report! The issue should be fixed now (tested against WindowsOS) - just to verify, please remove `.jarCache` folder again and update to latest as2f version from pub.dev.

Cheers!
